package configplan

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"reflect"
	"testing"
	"time"

	agentv1 "github.com/GentleKingson/ocservia/control-plane/gen/proto/ocserv/platform/agent/v1"
	configurationstore "github.com/GentleKingson/ocservia/control-plane/internal/configplan/store"
	"github.com/GentleKingson/ocservia/control-plane/internal/configprofile"
	"github.com/GentleKingson/ocservia/control-plane/internal/database"
	"github.com/GentleKingson/ocservia/control-plane/internal/database/value"
	"github.com/google/uuid"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

func TestCompleteApprovalRequiresMaterializedEvidenceAndBindsEntirePlan(t *testing.T) {
	service, store, result := approvalPlanFixture(t)
	store.plan.CandidateRedacted = "# generated by ocservia complete-config/v1\ndevice = vpns\n"
	result.DiffRedacted = safeDiff(store.plan.CandidateRedacted)
	result.MaterializedHash = bytes.Repeat([]byte{0x44}, 32)
	read := func() (ApprovalBinding, error) {
		var err error
		store.plan.Result, err = proto.Marshal(result)
		if err != nil {
			t.Fatal(err)
		}
		return service.ApprovalBinding(t.Context(), store.plan.ID)
	}
	binding, err := read()
	if err != nil {
		t.Fatal(err)
	}
	expires, err := store.plan.ExpiresAt.Time()
	if err != nil {
		t.Fatal(err)
	}
	want, err := configprofile.ApprovalHash(store.plan.ID, store.plan.NodeID, result.CandidateHash, result.MaterializedHash, result.CurrentHash, uint64(store.plan.ExpectedRevision), timestamppb.New(expires))
	if err != nil || !bytes.Equal(want, binding.RequestHash) || bytes.Equal(binding.RequestHash, result.CandidateHash) {
		t.Fatal("incomplete approval binding", err)
	}
	var summary map[string]any
	if json.Unmarshal(binding.RequestSummary, &summary) != nil || summary["plan_id"] != store.plan.ID.String() || summary["materialized_hash"] == nil {
		t.Fatal("missing approval summary", summary)
	}
	for _, change := range []func(){
		func() { store.plan.ID = uuid.Must(uuid.NewV7()) }, func() { store.plan.NodeID = uuid.Must(uuid.NewV7()) },
		func() { store.plan.ExpectedRevision++ }, func() { store.plan.ExpiresAt.Micros++ },
		func() { result.MaterializedHash[0] ^= 1 }, func() { result.CurrentHash[0] ^= 1 },
		func() { result.CandidateHash[0] ^= 1; store.plan.CandidateHash = bytes.Clone(result.CandidateHash) },
	} {
		change()
		changed, err := read()
		if err != nil || bytes.Equal(changed.RequestHash, binding.RequestHash) {
			t.Fatal("approval content change not bound", err)
		}
		binding = changed
	}
	for _, hash := range [][]byte{nil, make([]byte, 31), make([]byte, 33)} {
		result.MaterializedHash = hash
		if _, err := read(); !errors.Is(err, ErrApprovalNotReady) {
			t.Fatal("missing materialization accepted", err)
		}
	}
	result.MaterializedHash = bytes.Repeat([]byte{0x44}, 32)
	result.Warnings = []string{"secret_references_unresolved"}
	if _, err := read(); !errors.Is(err, ErrApprovalNotReady) {
		t.Fatal("partial native validation accepted", err)
	}
}

type approvalPlanBackend struct {
	database.Backend
	tx *approvalPlanTx
}

func (b approvalPlanBackend) Begin(_ context.Context, isolation database.Isolation) (database.Tx, error) {
	if isolation != database.ReadCommitted {
		return nil, database.ErrUnsupported
	}
	return b.tx, nil
}

type approvalPlanTx struct {
	database.Tx
	store *approvalPlanStore
}

func (t *approvalPlanTx) ConfigurationStore() configurationstore.Store { return t.store }
func (t *approvalPlanTx) Commit(context.Context) error                 { return nil }
func (t *approvalPlanTx) Rollback(context.Context) error               { return nil }

type approvalPlanStore struct {
	configurationstore.Store
	plan  configurationstore.Plan
	err   error
	ctx   context.Context
	id    uuid.UUID
	reads int
}

func (s *approvalPlanStore) Get(ctx context.Context, id uuid.UUID) (configurationstore.Plan, error) {
	s.ctx, s.id = ctx, id
	s.reads++
	return s.plan, s.err
}

func approvalPlanFixture(t *testing.T) (*Service, *approvalPlanStore, *agentv1.ConfigPlanResult) {
	t.Helper()
	warnings, err := value.ParseJSONB([]byte(`[]`))
	if err != nil {
		t.Fatal(err)
	}
	store := &approvalPlanStore{plan: configurationstore.Plan{
		ID:          uuid.MustParse("019fde50-1111-7111-8111-111111111111"),
		WorkspaceID: uuid.MustParse("019fde50-2222-7222-8222-222222222222"),
		NodeID:      uuid.MustParse("019fde50-3333-7333-8333-333333333333"),
		State:       "succeeded", ExpectedRevision: 7, CandidateHash: bytes.Repeat([]byte{0x43}, 32),
		CandidateRedacted: "# generated by ocservia config-plan/v1\ntcp-port = 443\nserver-key = <secret-ref:opaque>\n",
		Warnings:          warnings, ExpiresAt: value.Timestamp{Valid: true, Micros: 3600000000},
	}}
	result := &agentv1.ConfigPlanResult{CandidateHash: bytes.Clone(store.plan.CandidateHash), CurrentHash: bytes.Repeat([]byte{0x42}, 32), DiffRedacted: safeDiff(store.plan.CandidateRedacted), CurrentUnchanged: true, StagingCleaned: true}
	service := NewBackend(approvalPlanBackend{tx: &approvalPlanTx{store: store}}, nil)
	service.now = func() time.Time { return time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC) }
	return service, store, result
}

func TestApprovalBindingUsesInterpretedPlan(t *testing.T) {
	for _, tc := range []struct {
		name   string
		change func(*configurationstore.Plan, *agentv1.ConfigPlanResult)
	}{
		{"pending", func(p *configurationstore.Plan, _ *agentv1.ConfigPlanResult) { p.State = "queued" }},
		{"failed", func(p *configurationstore.Plan, _ *agentv1.ConfigPlanResult) { p.State = "failed" }},
		{"rejected", func(p *configurationstore.Plan, _ *agentv1.ConfigPlanResult) { p.State = "rejected" }},
		{"unknown", func(p *configurationstore.Plan, _ *agentv1.ConfigPlanResult) { p.State = "unknown" }},
		{"expired-state", func(p *configurationstore.Plan, _ *agentv1.ConfigPlanResult) { p.State = "expired" }},
		{"candidate-hash", func(_ *configurationstore.Plan, r *agentv1.ConfigPlanResult) { r.CandidateHash[0] ^= 0xff }},
		{"unsafe-diff", func(_ *configurationstore.Plan, r *agentv1.ConfigPlanResult) { r.DiffRedacted = "private key material" }},
		{"unsafe-warning", func(_ *configurationstore.Plan, r *agentv1.ConfigPlanResult) {
			r.Warnings = []string{"private key material"}
		}},
		{"current-changed", func(_ *configurationstore.Plan, r *agentv1.ConfigPlanResult) { r.CurrentUnchanged = false }},
		{"staging-not-clean", func(_ *configurationstore.Plan, r *agentv1.ConfigPlanResult) { r.StagingCleaned = false }},
		{"missing-current-hash", func(_ *configurationstore.Plan, r *agentv1.ConfigPlanResult) { r.CurrentHash = nil }},
		{"no-expiry", func(p *configurationstore.Plan, _ *agentv1.ConfigPlanResult) { p.ExpiresAt = value.Timestamp{} }},
		{"expired-time", func(p *configurationstore.Plan, _ *agentv1.ConfigPlanResult) { p.ExpiresAt.Micros = -1 }},
		{"exact-expiry", func(p *configurationstore.Plan, _ *agentv1.ConfigPlanResult) { p.ExpiresAt.Micros = 0 }},
		{"negative-infinity", func(p *configurationstore.Plan, _ *agentv1.ConfigPlanResult) {
			p.ExpiresAt.Micros = value.NegativeInfinity
		}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			service, store, result := approvalPlanFixture(t)
			tc.change(&store.plan, result)
			var err error
			store.plan.Result, err = proto.Marshal(result)
			if err != nil {
				t.Fatal(err)
			}
			binding, err := service.ApprovalBinding(t.Context(), store.plan.ID)
			if !errors.Is(err, ErrApprovalNotReady) || !reflect.DeepEqual(binding, ApprovalBinding{}) {
				t.Fatalf("invalid Plan exposed binding: %+v %v", binding, err)
			}
			if store.reads != 1 || store.ctx != t.Context() || store.id != store.plan.ID {
				t.Fatal("binding bypassed Get or changed read identity")
			}
		})
	}
	for _, payload := range [][]byte{nil, {0xff}} {
		service, store, _ := approvalPlanFixture(t)
		store.plan.Result = payload
		if binding, err := service.ApprovalBinding(t.Context(), store.plan.ID); !errors.Is(err, ErrApprovalNotReady) || !reflect.DeepEqual(binding, ApprovalBinding{}) {
			t.Fatalf("invalid result: %+v %v", binding, err)
		}
	}
	for _, readErr := range []error{database.ErrNotFound, database.ErrPermission, context.Canceled} {
		service, store, _ := approvalPlanFixture(t)
		store.err = readErr
		if binding, err := service.ApprovalBinding(t.Context(), store.plan.ID); !errors.Is(err, readErr) || !reflect.DeepEqual(binding, ApprovalBinding{}) {
			t.Fatalf("read error: %+v %v", binding, err)
		}
	}
}

func TestApprovalBindingGoldenAndExpiry(t *testing.T) {
	service, store, result := approvalPlanFixture(t)
	result.Warnings = []string{"secret_references_unresolved"}
	var err error
	store.plan.Result, err = proto.Marshal(result)
	if err != nil {
		t.Fatal(err)
	}
	// This pins the pre-refactor HTTP bytes, including map ordering, HTML escaping
	// and the timestamp encoding. The approval hash is the candidate, not summary SHA.
	wantSummary := `{"candidate_hash":"4343434343434343434343434343434343434343434343434343434343434343","current_hash":"4242424242424242424242424242424242424242424242424242424242424242","diff_redacted":"- \u003ccurrent configuration redacted\u003e\n+ tcp-port = 443\n+ server-key = \u003csecret-ref:opaque\u003e\n","expected_revision":7,"expires_at":"2000-01-01T01:00:00Z","node_id":"019fde50-3333-7333-8333-333333333333"}`
	binding, err := service.ApprovalBinding(t.Context(), store.plan.ID)
	if err != nil || binding.WorkspaceID != store.plan.WorkspaceID || binding.NodeID != store.plan.NodeID || !bytes.Equal(binding.RequestHash, bytes.Repeat([]byte{0x43}, 32)) || string(binding.RequestSummary) != wantSummary {
		t.Fatalf("binding changed: %+v %s %v", binding, binding.RequestSummary, err)
	}
	binding.RequestHash[0] ^= 0xff
	store.plan.ExpiresAt.Micros = 1
	if binding, err = service.ApprovalBinding(t.Context(), store.plan.ID); err != nil || !bytes.Equal(binding.RequestHash, store.plan.CandidateHash) {
		t.Fatalf("unexpired Plan: %+v %v", binding, err)
	}
	service.now = func() time.Time { return time.Date(2000, 1, 1, 0, 0, 0, 1000, time.UTC) }
	if _, err := service.ApprovalBinding(t.Context(), store.plan.ID); !errors.Is(err, ErrApprovalNotReady) {
		t.Fatalf("expiry was not checked again: %v", err)
	}
	store.plan.ExpiresAt.Micros = value.PositiveInfinity
	binding, err = service.ApprovalBinding(t.Context(), store.plan.ID)
	var summary map[string]any
	if err != nil || json.Unmarshal(binding.RequestSummary, &summary) != nil || summary["expires_at"] != "infinity" {
		t.Fatalf("infinity compatibility: %s %v", binding.RequestSummary, err)
	}
	service.now = func() time.Time { return time.Date(300000, 1, 1, 0, 0, 0, 0, time.UTC) }
	if binding, err := service.ApprovalBinding(t.Context(), store.plan.ID); err == nil || !reflect.DeepEqual(binding, ApprovalBinding{}) {
		t.Fatalf("invalid clock: %+v %v", binding, err)
	}
}
