package configplan

import (
	"github.com/google/uuid"
	"testing"
)

func TestRenderDeterministicAndRedacted(t *testing.T) {
	input := RenderInput{Template: Template{Name: "baseline", Directives: []Directive{
		{Name: "server-key", SecretRef: &SecretRef{ID: uuid.MustParse("01900000-0000-7000-8000-000000000001"), Provider: "node", Key: "tls/server", Version: "v1"}},
		{Name: "tcp-port", Value: "${PORT}"},
	}}, NodeVariables: map[string]string{"PORT": "443"}, OcservVersion: "1.3.0", Capabilities: []string{"config.network", "config.tls"}}
	first, err := Render(input)
	if err != nil {
		t.Fatal(err)
	}
	input.Template.Directives[0], input.Template.Directives[1] = input.Template.Directives[1], input.Template.Directives[0]
	second, err := Render(input)
	if err != nil {
		t.Fatal(err)
	}
	if first.Hash != second.Hash || string(first.Candidate) != string(second.Candidate) {
		t.Fatal("render is not deterministic")
	}
	if first.Redacted == string(first.Candidate) || contains(first.Redacted, "tls/server") {
		t.Fatal("secret reference was not redacted")
	}
}

func TestRenderRejectsInjectionAndUnsupportedDirective(t *testing.T) {
	base := RenderInput{Template: Template{Name: "bad", Directives: []Directive{{Name: "tcp-port", Value: "443\nrun-as-user = root"}}}, Capabilities: []string{"config.network"}}
	if _, err := Render(base); err == nil {
		t.Fatal("newline injection accepted")
	}
	base.Template.Directives[0] = Directive{Name: "config-file", Value: "/tmp/owned"}
	if _, err := Render(base); err == nil {
		t.Fatal("arbitrary path directive accepted")
	}
	base.Template.Directives[0] = Directive{Name: "tcp-port", SecretRef: &SecretRef{ID: uuid.MustParse("01900000-0000-7000-8000-000000000001"), Provider: "node", Key: "not-a-secret-port", Version: "v1"}}
	if _, err := Render(base); err == nil {
		t.Fatal("non-secret directive accepted SecretRef")
	}
}

func TestRenderEnforcesVersionAndCapabilityMatrix(t *testing.T) {
	input := RenderInput{Template: Template{Name: "matrix", Directives: []Directive{{Name: "cert-user-oid", Value: "1.2.3.4"}}}, OcservVersion: "1.2.4", Capabilities: []string{"config.tls"}}
	if _, err := Render(input); err == nil {
		t.Fatal("version-incompatible directive accepted")
	}
	input.OcservVersion = "1.3.0"
	input.Capabilities = nil
	if _, err := Render(input); err == nil {
		t.Fatal("missing directive capability accepted")
	}
}

func TestSafeDiffAndWarningsCannotCarrySecretMaterial(t *testing.T) {
	diff := safeDiff("# generated by ocservia config-plan/v1\nserver-key = <secret-ref:01900000-0000-7000-8000-000000000001:node:v1>\ntcp-port = 443\n")
	if contains(diff, "tls/server") || diff != "- <current configuration redacted>\n+ server-key = <secret-ref:01900000-0000-7000-8000-000000000001:node:v1>\n+ tcp-port = 443\n" {
		t.Fatalf("unsafe diff %q", diff)
	}
	if !safeValidationWarnings([]string{"secret_references_unresolved"}) || safeValidationWarnings([]string{"current secret: leaked"}) {
		t.Fatal("validation warning allowlist regressed")
	}
}

func contains(value, part string) bool {
	for i := 0; i+len(part) <= len(value); i++ {
		if value[i:i+len(part)] == part {
			return true
		}
	}
	return false
}
