package configplan

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const MaxCandidateBytes = 256 * 1024

var (
	ErrInvalid      = errors.New("configuration plan is invalid")
	namePattern     = regexp.MustCompile(`^[a-z][a-z0-9-]{0,63}$`)
	variablePattern = regexp.MustCompile(`\$\{([A-Za-z][A-Za-z0-9_]*)\}`)
)

// Directive is one typed Ocserv directive. Exactly one of Value and SecretRef is set.
type Directive struct {
	Name      string     `json:"name"`
	Value     string     `json:"value,omitempty"`
	SecretRef *SecretRef `json:"secret_ref,omitempty"`
}

// SecretRef names secret material without resolving or storing it.
type SecretRef struct {
	Provider string `json:"provider"`
	Key      string `json:"key"`
}

// Template is a bounded, non-executable configuration document.
type Template struct {
	Name       string      `json:"name"`
	Directives []Directive `json:"directives"`
}

type RenderInput struct {
	Template      Template          `json:"template"`
	NodeVariables map[string]string `json:"node_variables,omitempty"`
	OcservVersion string            `json:"ocserv_version"`
	Capabilities  []string          `json:"capabilities,omitempty"`
}

type Rendered struct {
	Candidate            []byte
	Redacted             string
	Hash                 [32]byte
	Warnings             []string
	RequiredCapabilities []string
}

var directiveCapabilities = map[string]string{
	"auth": "config.auth", "ca-cert": "config.tls", "cert-user-oid": "config.tls",
	"cookie-timeout": "config.sessions", "dns": "config.network", "ipv4-network": "config.network",
	"max-clients": "config.limits", "max-same-clients": "config.limits", "route": "config.network",
	"server-cert": "config.tls", "server-key": "config.tls", "socket-file": "config.runtime",
	"tcp-port": "config.network", "udp-port": "config.network",
}

// Render produces canonical LF-delimited output and a stable SHA-256 digest.
func Render(input RenderInput) (Rendered, error) {
	if !validLabel(input.Template.Name, 128) || len(input.Template.Directives) == 0 || len(input.Template.Directives) > 256 || len(input.NodeVariables) > 128 {
		return Rendered{}, ErrInvalid
	}
	variables := make(map[string]string, len(input.NodeVariables))
	for key, value := range input.NodeVariables {
		if !regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_]{0,63}$`).MatchString(key) || !validValue(value) {
			return Rendered{}, ErrInvalid
		}
		variables[key] = value
	}
	capabilities := make(map[string]bool, len(input.Capabilities))
	for _, capability := range input.Capabilities {
		capabilities[capability] = true
	}
	major, minor, observedVersion, err := supportedVersion(input.OcservVersion)
	if err != nil {
		return Rendered{}, err
	}
	directives := append([]Directive(nil), input.Template.Directives...)
	sort.SliceStable(directives, func(i, j int) bool { return directives[i].Name < directives[j].Name })
	var candidate, redacted strings.Builder
	candidate.WriteString("# generated by ocservia config-plan/v1\n")
	redacted.WriteString("# generated by ocservia config-plan/v1\n")
	warnings := make([]string, 0)
	requiredCapabilities := make(map[string]struct{})
	previous := ""
	for _, directive := range directives {
		if !namePattern.MatchString(directive.Name) || directive.Name == previous {
			return Rendered{}, ErrInvalid
		}
		previous = directive.Name
		required, supported := directiveCapabilities[directive.Name]
		if !supported {
			return Rendered{}, fmt.Errorf("%w: directive %q is not allowed", ErrInvalid, directive.Name)
		}
		if !capabilities[required] {
			return Rendered{}, fmt.Errorf("%w: directive %q requires %s", ErrInvalid, directive.Name, required)
		}
		requiredCapabilities[required] = struct{}{}
		if directive.Name == "cert-user-oid" && observedVersion && (major < 1 || major == 1 && minor < 3) {
			return Rendered{}, fmt.Errorf("%w: directive %q requires Ocserv 1.3 or newer", ErrInvalid, directive.Name)
		}
		if (directive.SecretRef == nil) == (directive.Value == "") {
			return Rendered{}, ErrInvalid
		}
		var value, safe string
		if directive.SecretRef != nil {
			if directive.Name != "server-key" && directive.Name != "server-cert" && directive.Name != "ca-cert" {
				return Rendered{}, fmt.Errorf("%w: directive %q cannot use SecretRef", ErrInvalid, directive.Name)
			}
			if !validLabel(directive.SecretRef.Provider, 64) || !validSecretKey(directive.SecretRef.Key) {
				return Rendered{}, ErrInvalid
			}
			value = "${secret:" + directive.SecretRef.Provider + ":" + directive.SecretRef.Key + "}"
			safe = "<secret-ref:" + directive.SecretRef.Provider + ">"
		} else {
			resolved, err := expand(directive.Value, variables)
			if err != nil || !validValue(resolved) {
				return Rendered{}, ErrInvalid
			}
			value, safe = resolved, resolved
		}
		candidate.WriteString(directive.Name + " = " + value + "\n")
		redacted.WriteString(directive.Name + " = " + safe + "\n")
	}
	if candidate.Len() > MaxCandidateBytes {
		return Rendered{}, ErrInvalid
	}
	if !observedVersion {
		warnings = append(warnings, "ocserv_version_unobserved")
	}
	bytes := []byte(candidate.String())
	required := make([]string, 0, len(requiredCapabilities)+1)
	required = append(required, "ocserv.config.plan")
	for capability := range requiredCapabilities {
		required = append(required, capability)
	}
	sort.Strings(required)
	return Rendered{Candidate: bytes, Redacted: redacted.String(), Hash: sha256.Sum256(bytes), Warnings: warnings, RequiredCapabilities: required}, nil
}

func supportedVersion(value string) (major, minor int, observed bool, err error) {
	value = strings.TrimSpace(value)
	if value == "" || value == "unknown" {
		return 0, 0, false, nil
	}
	parts := strings.Split(value, ".")
	if len(parts) != 3 {
		return 0, 0, true, ErrInvalid
	}
	major, err = strconv.Atoi(parts[0])
	if err != nil {
		return 0, 0, true, ErrInvalid
	}
	minor, err = strconv.Atoi(parts[1])
	if err != nil {
		return 0, 0, true, ErrInvalid
	}
	if _, patchErr := strconv.Atoi(parts[2]); patchErr != nil || major != 1 || minor < 2 || minor > 4 {
		return 0, 0, true, fmt.Errorf("%w: unsupported Ocserv version", ErrInvalid)
	}
	return major, minor, true, nil
}

func expand(value string, variables map[string]string) (string, error) {
	missing := false
	result := variablePattern.ReplaceAllStringFunc(value, func(match string) string {
		key := variablePattern.FindStringSubmatch(match)[1]
		replacement, ok := variables[key]
		if !ok {
			missing = true
			return ""
		}
		return replacement
	})
	if missing || strings.Contains(result, "${") {
		return "", ErrInvalid
	}
	return result, nil
}

func validValue(value string) bool {
	return value != "" && len(value) <= 4096 && !strings.ContainsAny(value, "\r\n\x00") && !strings.Contains(value, "{{") && !strings.Contains(value, "}}")
}

func validLabel(value string, max int) bool {
	value = strings.TrimSpace(value)
	return value != "" && len(value) <= max && regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*$`).MatchString(value)
}

func validSecretKey(value string) bool {
	return len(value) <= 256 && regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._/-]*$`).MatchString(value) && !strings.Contains(value, "..")
}

func HashHex(hash [32]byte) string { return hex.EncodeToString(hash[:]) }
