[Service]
EnvironmentFile=/etc/ocservia-agent/relays.env
ExecStart=
ExecStart=/usr/libexec/ocservia/ocservia-agent --controller $CONTROLLER_ENDPOINT_ID --node-id $NODE_ID --relay-mode custom --relay-url $RELAY_URL_A --relay-url $RELAY_URL_B --relay-token-file /etc/ocservia-agent/relay-access-token
