#!/usr/bin/env bash
# Quick install: one integrated, bundled PostgreSQL, ACME, root-lifecycle
# Controller with two initial Local administrators. It is a preset over the
# existing authorities, not a second installer: bootstrap-host.sh prepares the
# host, quick-materials.sh creates the protected material, install.sh and
# controller.sh activate, and the Controller one-shots create the management
# workspace and the Local administrators.
#
# Every step is idempotent, so rerunning the same command after an
# interruption continues it. The generated /etc/ocservia/install.env is the
# record of a Quick installation; a different deployment is refused.
#
# Usage (normally through controller-bootstrap.sh --quick):
#   quick-install.sh --controller-domain NAME --relay-domain NAME
#     --acme-email ADDRESS [--root-ca-passphrase-file PATH]
#     [--root-ca-export-dir PATH] [--release-file PATH]
# --release-file activates a local release manifest with controller.sh instead
# of install.sh downloading the checkout tag's Release (release acceptance).
# OCSERV_ACME_DIRECTORY_URL and OCSERV_ACME_CA_FILE select a private ACME
# directory on the first run (test servers such as Pebble).
set -euo pipefail
umask 077

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG_DIR=/etc/ocservia
CONFIG="${CONFIG_DIR}/install.env"
CREDENTIALS_DIR=/root/ocservia-initial-credentials
STATE_ROOT=/var/lib/ocservia-controller
HEADER="# ocservia Quick install configuration (generated; keep unchanged)"

fail() { echo "quick install: $*" >&2; exit 1; }
note() { echo "quick install: $*"; }

controller_domain="" relay_domain="" acme_email="" release_file=""
materials_args=()
original_args=("$@")
while (($#)); do
  (($# >= 2)) || fail "missing value for $1"
  case "$1" in
    --controller-domain) controller_domain="$2" ;;
    --relay-domain) relay_domain="$2" ;;
    --acme-email) acme_email="$2" ;;
    --root-ca-passphrase-file) materials_args+=("$1" "$2" --non-interactive) ;;
    --root-ca-export-dir) materials_args+=("$1" "$2") ;;
    --release-file) release_file="$2" ;;
    *) fail "unknown argument: $1" ;;
  esac
  shift 2
done
[[ -n "${controller_domain}" && -n "${relay_domain}" && -n "${acme_email}" ]] ||
  fail "--controller-domain, --relay-domain and --acme-email are required"
[[ -z "${release_file}" || ("${release_file}" == /* && -f "${release_file}") ]] ||
  fail "--release-file must be an absolute path to a release manifest"

if ((EUID != 0)); then
  command -v sudo >/dev/null 2>&1 || fail "run as root or install sudo"
  exec sudo env ${OCSERV_ACME_DIRECTORY_URL:+"OCSERV_ACME_DIRECTORY_URL=${OCSERV_ACME_DIRECTORY_URL}"} \
    ${OCSERV_ACME_CA_FILE:+"OCSERV_ACME_CA_FILE=${OCSERV_ACME_CA_FILE}"} "$0" "${original_args[@]}"
fi

# As in install.sh --root-lifecycle: provision the state root for root, while
# SUDO_UID keeps git's trust in a launcher-owned checkout.
unset SUDO_USER
# Only the generated configuration applies; ambient settings never leak in.
acme_directory="${OCSERV_ACME_DIRECTORY_URL:-}" acme_ca="${OCSERV_ACME_CA_FILE:-}"
while IFS= read -r variable; do
  [[ "${variable}" != OCSERV_* ]] || unset "${variable}"
done < <(compgen -e)

config_keys=(OCSERV_DEPLOYMENT_MODE OCSERV_DATABASE_BACKEND OCSERV_DATABASE_DEPLOYMENT OCSERV_TLS_MODE
  OCSERV_ACME_EMAIL OCSERV_ACME_DIRECTORY_URL OCSERV_ACME_CA_FILE OCSERV_PUBLIC_HOST OCSERV_RELAY_PUBLIC_HOST
  OCSERV_LOCAL_AUTH_ENABLED OCSERV_SECRET_DIR OCSERV_RELAY_SECRET_DIR OCSERV_SIGNER_SECRET_DIR
  OCSERV_SIGNER_STATE_DIR OCSERV_BACKUP_DIR OCSERV_AUDIT_EVENT_KEY_ID OCSERV_CONTROLLER_ENDPOINT_ID)

if [[ -e "${CONFIG}" || -L "${CONFIG}" ]]; then
  [[ -f "${CONFIG}" && ! -L "${CONFIG}" && "$(head -n 1 -- "${CONFIG}")" == "${HEADER}" ]] ||
    fail "${CONFIG} was not generated by the Quick install; use the manual installation"
  for line in "OCSERV_PUBLIC_HOST=${controller_domain}" "OCSERV_RELAY_PUBLIC_HOST=${relay_domain}" \
    "OCSERV_ACME_EMAIL=${acme_email}"; do
    grep -qxF -- "${line}" "${CONFIG}" || fail "${CONFIG} records different domains or email; rerun with the original values"
  done
  note "continuing the Quick installation recorded in ${CONFIG}"
elif [[ -e "${STATE_ROOT}/deployment-profile.json" || -e "${STATE_ROOT}/current-release.json" ]]; then
  fail "a Controller deployment already exists in ${STATE_ROOT}; Quick only installs a new host"
fi

secret_dir="${CONFIG_DIR}/secrets"
relay_dir="${CONFIG_DIR}/relay"
signer_dir="${CONFIG_DIR}/signer"
signer_state=/var/lib/ocservia-signer
backup_dir=/var/backups/ocservia

# Host tools (jq, openssl, Docker) come from the host bootstrap. install.sh
# runs it again; it is idempotent.
"${ROOT}/deploy/production/bootstrap-host.sh" install --backup-dir "${backup_dir}"

install -d -o 0 -g 0 -m 0755 -- "${CONFIG_DIR}"
[[ -d "${relay_dir}" ]] || install -d -o 0 -g 0 -m 0700 -- "${relay_dir}"
OCSERV_SECRET_DIR="${secret_dir}" OCSERV_SIGNER_SECRET_DIR="${signer_dir}" OCSERV_SIGNER_STATE_DIR="${signer_state}" \
  "${ROOT}/deploy/production/quick-materials.sh" ${materials_args[@]+"${materials_args[@]}"}

if [[ ! -e "${CONFIG}" ]]; then
  endpoint_id="$(jq -er '.controller_endpoint_id' "${secret_dir}/quick-install.json")"
  staged="$(mktemp "${CONFIG_DIR}/.install.env.XXXXXX")"
  {
    printf '%s\n' "${HEADER}"
    printf '%s\n' OCSERV_DEPLOYMENT_MODE=integrated OCSERV_DATABASE_BACKEND=postgres \
      OCSERV_DATABASE_DEPLOYMENT=bundled OCSERV_TLS_MODE=acme "OCSERV_ACME_EMAIL=${acme_email}"
    [[ -z "${acme_directory}" ]] || printf 'OCSERV_ACME_DIRECTORY_URL=%s\n' "${acme_directory}"
    [[ -z "${acme_ca}" ]] || printf 'OCSERV_ACME_CA_FILE=%s\n' "${acme_ca}"
    printf '%s\n' "OCSERV_PUBLIC_HOST=${controller_domain}" "OCSERV_RELAY_PUBLIC_HOST=${relay_domain}" \
      OCSERV_LOCAL_AUTH_ENABLED=true "OCSERV_SECRET_DIR=${secret_dir}" "OCSERV_RELAY_SECRET_DIR=${relay_dir}" \
      "OCSERV_SIGNER_SECRET_DIR=${signer_dir}" "OCSERV_SIGNER_STATE_DIR=${signer_state}" \
      "OCSERV_BACKUP_DIR=${backup_dir}" "OCSERV_AUDIT_EVENT_KEY_ID=quick-$(date -u +%Y%m%d)" \
      "OCSERV_CONTROLLER_ENDPOINT_ID=${endpoint_id}"
  } >"${staged}"
  mv -fT -- "${staged}" "${CONFIG}"
  note "configuration written: ${CONFIG}"
fi

# shellcheck source=../lib/install-env.sh disable=SC1091
source "${ROOT}/deploy/lib/install-env.sh"
install_env_load "${CONFIG}" "${config_keys[@]}"

if [[ -e "${STATE_ROOT}/current-release.json" ]]; then
  :
elif [[ -n "${release_file}" ]]; then
  "${ROOT}/deploy/production/controller.sh" install --release-file "${release_file}"
else
  (cd -- "${CONFIG_DIR}" && "${ROOT}/deploy/production/install.sh" --root-lifecycle)
fi

# Direct compose.sh commands need the installed release's images.
for role in gateway control transport backup postgres otel edge relay signer; do
  variable="OCSERV_${role^^}_IMAGE"
  printf -v "${variable}" '%s' "$(jq -er --arg role "${role}" '.images[$role]' "${STATE_ROOT}/current-release.json")"
  export "${variable?}"
done
compose() { "${ROOT}/deploy/production/compose.sh" "$@"; }

if [[ -e "${CREDENTIALS_DIR}/complete" ]]; then
  note "initial Local administrators already exist"
else
  workspace_id="$(compose run --rm --no-deps -T migrate --provision-management-workspace |
    jq -Rr 'fromjson? | select(.msg == "management workspace ready") | .workspace_id')"
  [[ "${workspace_id}" =~ ^[0-9a-f-]{36}$ ]] || fail "the management workspace was not provisioned"

  [[ -d "${CREDENTIALS_DIR}" ]] || install -d -o 0 -g 0 -m 0700 -- "${CREDENTIALS_DIR}"
  # Passwords are kept before bootstrap, so a retry reuses the same ones.
  for account in admin approver; do
    file="${CREDENTIALS_DIR}/${account}.txt"
    if [[ ! -e "${file}" ]]; then
      staged="$(mktemp "${CREDENTIALS_DIR}/.${account}.XXXXXX")"
      printf 'URL: https://%s\nUsername: initial-%s\nPassword: %s\n' \
        "${controller_domain}" "${account}" "$(openssl rand -hex 32)" >"${staged}"
      chmod 0400 -- "${staged}"
      mv -fT -- "${staged}" "${file}"
    fi
    sed -n 's/^Password: //p' "${file}" |
      install -o 65534 -g 65532 -m 0400 /dev/stdin "${secret_dir}/local-bootstrap-${account}-password"
  done
  trap 'rm -f -- "${secret_dir}"/local-bootstrap-{admin,approver}-password' EXIT
  status=0
  output="$(compose run --rm --no-deps -T \
    -e OCSERV_LOCAL_BOOTSTRAP_USERNAME=initial-admin \
    -e "OCSERV_LOCAL_BOOTSTRAP_WORKSPACE_ID=${workspace_id}" \
    -e OCSERV_LOCAL_BOOTSTRAP_PASSWORD_FILE=/run/secrets/local-bootstrap-password \
    -e OCSERV_LOCAL_BOOTSTRAP_APPROVER_USERNAME=initial-approver \
    -e OCSERV_LOCAL_BOOTSTRAP_APPROVER_PASSWORD_FILE=/run/secrets/local-bootstrap-approver-password \
    -v "${secret_dir}/local-bootstrap-admin-password:/run/secrets/local-bootstrap-password:ro" \
    -v "${secret_dir}/local-bootstrap-approver-password:/run/secrets/local-bootstrap-approver-password:ro" \
    control-plane --bootstrap-local-admin)" || status=$?
  printf '%s\n' "${output}"
  if ((status != 0)); then
    # Only this host's Quick run initializes Local authentication with the
    # passwords kept above, so an initialized state means an earlier run
    # committed before it could record completion.
    jq -Rr 'fromjson? | .error // empty' <<<"${output}" | grep -qxF "Local authentication is already initialized" ||
      fail "Local bootstrap was rejected"
    note "Local authentication was already initialized by an earlier run"
  fi
  : >"${CREDENTIALS_DIR}/complete"
fi

cat <<EOF
Quick install complete: https://${controller_domain}
Initial Local administrators (passwords only in these root-only files):
  initial-admin     ${CREDENTIALS_DIR}/admin.txt
  initial-approver  ${CREDENTIALS_DIR}/approver.txt
Give the two accounts to different responsible people and change both
passwords after the first login; nothing forces that change.
EOF
