package app

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/google/uuid"
)

// Published nodes cannot validate a complete real Ocserv configuration with
// the v1 directive allowlist. Prove fail-closed behavior, not successful apply.
func (f *controllerE2E) configRejectionWorkflow(nodePath string) {
	f.t.Helper()
	before, err := os.ReadFile("/etc/ocserv/ocserv.conf")
	if err != nil {
		f.t.Fatal(err)
	}
	node := f.api(f.admin, "GET", nodePath, nil, nil, http.StatusOK)
	revision, ok := node["config_revision"].(float64)
	if !ok || revision != 0 || node["version"] == revision {
		f.t.Fatal("configuration revision zero must be observed separately from authorization version")
	}
	create := map[string]any{
		"expected_revision": revision + 1, "ttl_seconds": 600, "reason": "published config revision and safe rejection",
		"template": map[string]any{"name": "published-config", "directives": []map[string]string{{"name": "tcp-port", "value": "44443"}}},
	}
	problem := f.api(f.admin, "POST", nodePath+"/config-plans", create, map[string]string{"Idempotency-Key": uuid.NewString()}, http.StatusConflict)
	if problem["type"] != "https://ocservia.dev/problems/stale-revision" {
		f.t.Fatal("stale configuration revision did not fail explicitly")
	}
	create["expected_revision"] = revision
	headers := map[string]string{"Idempotency-Key": uuid.NewString()}
	plan := f.api(f.admin, "POST", nodePath+"/config-plans", create, headers, http.StatusAccepted)
	candidate := []byte("# generated by ocservia config-plan/v1\ntcp-port = 44443\n")
	if plan["candidate_hash"] != fmt.Sprintf("%x", sha256.Sum256(candidate)) {
		f.t.Fatal("configuration rejection fixture did not match the dispatched candidate")
	}
	parserPath := f.file("rejected-candidate.conf", candidate, 0, 0, 0600)
	parserOutput, parserErr := f.command(0, 0, nil, "/usr/sbin/ocserv", "-t", "-c", parserPath).CombinedOutput()
	if _, ok := parserErr.(*exec.ExitError); !ok {
		f.t.Fatalf("real parser did not reject the incomplete candidate: %v", parserErr)
	}
	if err := os.WriteFile(filepath.Join(f.artifacts, "config-parser-rejection.txt"), parserOutput, 0600); err != nil {
		f.t.Fatal(err)
	}
	id := e2eString(f.t, plan, "id")
	if replay := f.api(f.admin, "POST", nodePath+"/config-plans", create, headers, http.StatusAccepted); replay["id"] != id {
		f.t.Fatal("configuration plan replay changed identity")
	}
	path := "/api/v1/config-plans/" + id
	f.wait("published node rejects incomplete real Ocserv config", func() bool {
		plan = f.api(f.admin, "GET", path, nil, nil, http.StatusOK)
		switch plan["state"] {
		case "failed", "rejected", "unknown":
			return true
		case "succeeded", "expired":
			f.t.Fatalf("unexpected configuration plan result: %v", plan)
		}
		return false
	})
	// Historical privd does not attest adapter errors. The Agent therefore
	// retains Unknown instead of trusting an unauthenticated failure as final.
	if plan["state"] == "unknown" {
		op := f.api(f.admin, "GET", "/api/v1/operations/"+id, nil, nil, http.StatusOK)
		commandID := strings.ReplaceAll(e2eString(f.t, op, "command_id"), "-", "")
		data, err := os.ReadFile(filepath.Join(f.artifacts, "agent.log"))
		if err != nil {
			f.t.Fatal(err)
		}
		matched := false
		for _, line := range bytes.Split(data, []byte("\n")) {
			var record struct {
				Fields map[string]any `json:"fields"`
			}
			if json.Unmarshal(line, &record) == nil && record.Fields["command_id"] == commandID && record.Fields["error_code"] == "privd_receipt_missing_or_malformed" {
				matched = true
			}
		}
		if !matched || op["state"] != "unknown" {
			f.t.Fatal("configuration Unknown lacked the expected missing-receipt evidence")
		}
	}
	if plan["validation"] == "valid" || plan["approval_id"] != nil {
		f.t.Fatal("failed configuration plan became approvable")
	}
	problem = f.api(f.admin, "POST", path+"/apply", map[string]any{
		"approval_id": uuid.Must(uuid.NewV7()).String(), "reason": "failed plan must never apply",
	}, map[string]string{"Idempotency-Key": uuid.NewString()}, http.StatusConflict)
	if problem["type"] != "https://ocservia.dev/problems/stale-revision" {
		f.t.Fatal("invalid configuration plan was not refused before apply")
	}
	after, err := os.ReadFile("/etc/ocserv/ocserv.conf")
	if err != nil || !bytes.Equal(before, after) {
		f.t.Fatal("rejected configuration workflow changed real config", err)
	}
	node = f.api(f.admin, "GET", nodePath, nil, nil, http.StatusOK)
	if node["config_revision"] != revision {
		f.t.Fatal("rejected configuration workflow advanced revision")
	}
	staging, err := filepath.Glob("/etc/ocserv/.ocservia-plan-*")
	if err != nil || len(staging) != 0 {
		f.t.Fatal("failed configuration plan left staging files", err)
	}
	evidence, err := json.MarshalIndent(map[string]any{
		"plan": plan, "node": node, "apply_rejection": problem,
		"config_unchanged": true, "successful_apply_tested": false,
	}, "", "  ")
	if err != nil {
		f.t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(f.artifacts, "config-rejection.json"), evidence, 0600); err != nil {
		f.t.Fatal(err)
	}
	f.t.Log("config revision zero, stale revision refusal, exact replay, real parser rejection, denied apply and unchanged file/revision passed; positive apply unsupported")
}
