#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/env.sh
source "${ROOT}/scripts/env.sh"

(cd "${ROOT}/proto" && buf generate --template buf.gen.yaml)

cat >"${ROOT}/rust/crates/contracts/src/generated/mod.rs" <<'EOF'
// Generated by scripts/generate.sh. DO NOT EDIT.

pub mod ocserv {
    pub mod platform {
        pub mod agent {
            pub mod v1 {
                include!("ocserv/platform/agent/v1/ocserv.platform.agent.v1.rs");
            }
        }
        pub mod transport {
            pub mod v1 {
                include!("ocserv/platform/transport/v1/ocserv.platform.transport.v1.rs");
            }
        }
    }
}
EOF

rm -rf "${ROOT}/web/src/api/generated"
mkdir -p "${ROOT}/web/src/api/generated"
java -jar "${ROOT}/.tools/openapi-generator-cli-$(sed -n 's/^openapi_generator=//p' "${ROOT}/toolchains.lock").jar" \
  generate \
  --generator-name typescript-fetch \
  --input-spec "${ROOT}/openapi/openapi.yaml" \
  --output "${ROOT}/web/src/api/generated" \
  --config "${ROOT}/openapi/generator-config.yaml" \
  --additional-properties=useSingleRequestParameter=true \
  --global-property=apiDocs=false,modelDocs=false,apiTests=false,modelTests=false \
  --skip-validate-spec

rm -rf "${ROOT}/web/src/api/generated/.openapi-generator"
rm -f "${ROOT}/web/src/api/generated/.openapi-generator-ignore"
(cd "${ROOT}/web" && \
  npx --no-install prettier --write src/api/generated >/dev/null)
